version: '3.8'
services:
  mail-service:
    build: .
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - elasticsearch
      - rabbitmq
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: mail-service

#      SPRING_CONFIG_IMPORT: optional:consul:/
#      SPRING_CLOUD_CONSUL_HOST: consul
#      SPRING_CLOUD_CONSUL_PORT: 8500

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      SPRING_ELASTICSEARCH_URI: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_USERNAME: ""
      SPRING_ELASTICSEARCH_PASSWORD: ""
    networks:
      - shared-net


  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - shared-net
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - shared-net

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - shared-net

volumes:
  es_data:

networks:
  shared-net:
    external: true